### ISSUE TITLE
about you mfc-node and cb-node

### ISSUE THREAD

**Issue by marabu88** [sstativa/showuptv-node#1]
sorry. i write am here. what happened?
i see this message "Repository unavailable due to DMCA takedown."
you have any other places for this?

**Comment by marabu88** [comment]
What should we do now?
How long ago did this happen?

**Comment by Damianonymous** [comment]
I noticed it about 10 days ago. I think you have to wait, if you update websites, look for solutions on these forums:

http://stream-recorder.com
https://www.reddit.com/

**Comment by H4rm10d** [comment]
stream-recorder.com has gone offline, any other places?

**Comment by Damianonymous** [comment]
The forum is active again. Check my archives, I have saved in them the latest deleted files that are still working. Look at my stars, you will find there a few updated versions of CB and MFC recording programs, eg ctbrec, streamdvr etc.
