### ISSUE TITLE
Новая версия

### ISSUE THREAD

**Issue by Doodik** [sstativa/showuptv-node#5]
Спасибо разработчику, что внёс изменения в скрипт.
Есть два предложения:
1. У меня была ошибка, есть ники девушек, что начинаются с - (тире): -nik
2. Список моделей, лучше положить в отдельный файл. Когда добавляешь туда модель, приходиться перезапускать скрипт. Это не очень удобно.

**Comment by Doodik** [comment]
А ещё есть такая ошибка https://yadi.sk/i/isO0Ftbt3ZyLgh

**Comment by sstativa** [comment]
1. I'm not sure where and how "-" creates an error.
2. Now `config.yml` reloads with every "cicle" (based on `modelScanInterval`).
3. The last error is possible for node < v8. Either upgrade node to > v8, or disable debug mode `debug: false` in `config.yml`. Either way, it is not critical.

**Comment by Doodik** [comment]
Сергей, а обновления планируются? Если да, то когда их ожидать?
