### ISSUE TITLE
error: startChildBug is unavailable

### ISSUE THREAD

**Issue by nonso1bo** [sstativa/showuptv-node#7]
Hi, i'm getting this error: **startChildBug is unavailable** 
It happens regardless of which model i add in the config file.
Looks like the regexp at line 50 is failing. what can i do?
Thanks for your works btw

**Comment by Doodik** [comment]
(((

**Comment by Doodik** [comment]
У Сергея видимо нет времени на поддержку бесплатного ПО. Или, он ждет, когда сайт перестанет обновляться.

**Comment by Doodik** [comment]
@nonso1bo такая проблема у всех, уже почти месяц. Сейчас вернулась на сайт sweetpussy и мне тоже есть необходимость в этом скрипте.

**Comment by nonso1bo** [comment]
@Doodik как жаль, это приложение было здорово. проблема также в том, что нет даже веб-сайта, на котором вы можете загружать видеоролики showup.tv.

**Comment by Doodik** [comment]
https://github.com/sstativa/showuptv-node/issues/7#issuecomment-419526776 я точно уверен, что мы не одни! Очень много людей пользовались этим ПО

**Comment by Damianonymous** [comment]
В качестве альтернативного варианта вы можете использовать настраиваемый плагин Streamlink: 
https://github.com/Damianonymous/streamlink-plugins
Вы также можете попросить загрузить частные видео с camwhores.tv здесь:
http://board.hvgbook.net/?10-0-33708-0

**Comment by fapkamaster** [comment]
@Damianonymous Very inconvienient... I tried that StreamerLink (portable version for Windows), but it does fail to do anything. I have put your files to plugins... but it's too confusing. Also, pasting arguments is argh... 

It's better to use userscript* that adds button on streamer's page, to copy direct URL for stream (rtmp link)... and paste that on VLC screen, hit Enter/Play and will play. Same goes for download, just use IDM or Jaksta, or similar application.
* - I just need to rework that - on Firefox it does move screen down and it does not gather new URL, if streamer gets one after break/private show.

**Comment by Damianonymous** [comment]
@fapkamaster Możliwe że pobrałeś w momencie, kiedy testowałem inny kod, pobierz jeszcze raz. Możliwe też, że zapomniałeś dodać zmienne środowiskowe, choć ja obstawiam trzecią możliwość - używasz nieobsługiwanego XP-ka ;) Posiadając wtyczkę Streamlink, istnieje wiele możliwości łatwego nagrywania, np. taki prosty skrypt: https://github.com/Damianonymous/streamlink-plugins/tree/master/Recorder albo gotowe GUI do odtwarzania i nagrywania: https://xstreamloader.techweb.at/en/

**Comment by fapkamaster** [comment]
Nadal nic się nie dzieje... przynajmniej wtedy jakieś errory szły. A teraz czysto... 
Niby ten "prosty skrypt" nagrywa, a pliku nie widać.

Nie dość, że trzeba wpieprzyć ileś-tam "modułów", to jeszcze nie działa, graficznie nie przyjemne... (nawet z GUI). Czasami w ogóle brak opisów co należy zrobić, i co, ja mam się samemu domyślić?... Nie wiem czemu ludzie tego nie robią idiotoodpornego :( 

O wiele lepiej mieć w przeglądarce TamperMonkey ze skryptem, tego IDMa/cokolwiek i nacisnąć przycisk pod transmisją (działa na grupowe i privki)... a potem wsadzić IDM, wkleić i już* => wychodzi szybciej i jaśniej.
'* - no, trzeba ustawić by nie musieć potwierdzać, etc. Ale to jeden czy dwa kliki więcej, to niewiele.

Ale każdy orze jak może.

**Comment by Damianonymous** [comment]
Klikasz skrypt, wybierasz numerek modelki, Enter i leci 24/7, cała filozofia :) To akurat najprostsze, darmowe rozwiązania do transmisji publicznych ;)

https://s33.postimg.cc/m6bw08jen/Bez_tytu_u.jpg

**Comment by fapkamaster** [comment]
... teraz to mnie uznałeś za ciemniaka :( wiem, że .bat się odpala, wiem, że wybiera się z listy - wpisałem tam jedną osobę testowo... wybrałem ją i zatwierdziłem, ale nic się nie dzieje :) pokazuje nazwę pliku, który nie istnieje nigdzie (a w szczególności nie we wskazanej lokalizacji).

To co masz poniżej ############ się nie wyświetla.

Nie zmienia to faktu, że trzeba ręcznie wrzucać, zamiast mieć gotową działającą paczkę z ewentualną instrukcją konfiguracji... po co każdy z osobna ma to robić? Dziwną praktykę mają ludzie z githuba...

**Comment by Doodik** [comment]
Как задействовать твой плагин для стримлинка?
Я скачал showup.py . Теперь его нужно куда-то положить? Или как-то включить?

**Comment by Doodik** [comment]
Пишет: no plagin can handle URL: шоуап

**Comment by Damianonymous** [comment]
@Doodik  Вы должны скачать приложение: https://github.com/streamlink/streamlink/releases
Создавайте папки и вставляйте плагин Showup.py в C:\Users\User\AppData\Roaming\Streamlink\plugins\

**Comment by Doodik** [comment]
То есть зациклить не саму запись, а генерацию адреса потока. Если rtmpdump не знает такой адрес, значит на запись и наоборот

**Comment by Doodik** [comment]
@Damianonymous слились? Ждем Сергея

**Comment by sstativa** [comment]
I have no interest or time to work on this project. The script was made originally as a quick modification of __chaturbate-node__. I did not plan to do any further development of the script, and I've made some changes in the past only because they were a small one.

The current version of the site made automated recording "almost" impossible. The script has to be logged in to be able to record multiple streams, however it's not possible because of Google captcha.
I made a quick test and "passed" cookies from the browser to the script, but the site "spotted" this and refused the access (Probably it could work if I copied all headers, but I did not try this).

So far, the only solution that I think might work is some browser extension that will collect parameters and pass them to the script for recording. However, as I mentioned before I have no time to work on it.
May be someone will come up with a better idea. 

As for now, you might try to manually record streams via `rtmpdump`, in theory it should work.
Just grub a link from Inspector that looks like this
wss://cdn-e06.showup.tv/h5live/stream/?url=rtmp%3A%2F%2F__cdn-t01.showup.tv__%3A1935%2Fwebrtc&stream=**c22921174bdaa1cb08cb67ecd0561869_aac** &cid=__429284__&pid=__63520806036__ then create a command

rtmpdump --live --rtmp rtmp://__cdn-t01.showup.tv__:1935/webrtc --playpath __c22921174bdaa1cb08cb67ecd0561869_aac__ -C N:__429284__ -C N:__63520806036__ --flv ./rec.flv

**Comment by fapkamaster** [comment]
> So far, the only solution that I think might work is some browser extension that will collect parameters and pass them to the script for recording. However, as I mentioned before I have no time to work on it.
> May be someone will come up with a better idea.
Why?
You can "enter" main site and grab these links for all streams (public ones) with command [example]:
`$('li[transcoderaddr][streamid]').each((i, e) => console.log($(e).find('.stream__meta h4').text() + " @ " + "rtmp://" + e.getAttribute('transcoderaddr') + '/webrtc/' + e.getAttribute('streamid') + "_aac"));`
It gives result in console of: name @ full-rtmp-link

RTMP link alone is sufficient to start download in IDM. No need for other parameters.

**Comment by sstativa** [comment]
@fapkamaster I used your approach to modify the script. In theory it should work fine, but I did not try to properly test it, however, the short test worked fine for me.

**Comment by fapkamaster** [comment]
Yeah, it's working. I made a short test =)
Thank you =)
