### ISSUE TITLE
June 2019 Update

### ISSUE THREAD

**Issue by fapkamaster** [sstativa/showuptv-node#9]
Hello.
Showup.tv had update (to appearance it is minor, but some DIVs and functions have been changed).
So node does not work again.

Later, I will work for manual fix of this problem (so anyone reading this will be able to apply fixes himself/herself).
Hopefully Sergey will update whole node.

**Comment by fapkamaster** [comment]
Ok, I think I located problem:
`http://showup.tv/site/accept_rules/yes?ref=http://showup.tv/site/log_in`
There is no such URL to accept rules anymore...
Therefore it doesn't even reach main page... do not know how to fix. 

```<div class="clearfix"><form action="" method="post" id="acceptrules">
<input type="hidden" name="decision" value="true"></form>
<a class="btn btn--blue right" href="javascript:void(0)" onclick="document.getElementById('acceptrules').submit()">Wchodzę</a>
<a class="btn btn--white right" href="http://google.pl" rel="nofollow">Rezygnuję</a></div>```

**Comment by sstativa** [comment]
I made some changes. It should work but I did not test it for long.

**Comment by fapkamaster** [comment]
> I made some changes. It should work but I did not test it for long.

It works =)
Thank you :+1:
